name: multi-attribute-image-generation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - opencv
  - pillow
  - matplotlib
  - transformers
  - tensorboard
  - redis
  - geoip2
  - flask
  - scikit-learn
  - numpy
  - requests
  - openai
  - fastapi
  - pip:
    - GPUtil
    - openai-clip
    - user-agents
